# Basic Vector Search from Scratch

For this exercise we will implement basic vector search
from scratch with just numpy.<br/>
This will give us a feel
for what's happening under the hood in vector databases.

In [1]:
# !pip install numpy pytest [This is preinstalled for you in the workspace]

## Euclidean distance

There are many ways to measure the distance between two vectors.
Let's write a function that computes the `Euclidean distance` 
between vectors. 

This function should take as input two vectors and return
the euclidean distance between them.

For more details you can read this [kaggle page](https://www.kaggle.com/code/paulrohan2020/euclidean-distance-and-normalizing-a-vector)


In [20]:
import numpy as np
import pandas as pd

In [38]:
def euclidean_distance(v1: np.ndarray, v2: np.ndarray) -> float:
    """
    Compute the Euclidean distance between two vectors.

    Parameters
    ----------
    v1 : np.ndarray
        First vector.
    v2 : np.ndarray
        Second vector.

    Returns
    -------
    float
        Euclidean distance between `v1` and `v2`.
    """
    euclidean_distance = np.sum((v1 - v2)**2)**1/2
    return euclidean_distance

## KNN search

Using the distance function you just wrote, write a function that 
finds the k-nearest neighbors of a query vector.

This function should take as input a query vector, a 2d array of database vectors,
and an integer k the number of nearest neighbors to return. And it should return 
the vectors that are the k-nearest neighbors of the query vector.


In [8]:
def find_nearest_neighbors(query: np.ndarray,
                           vectors: np.ndarray,
                           k: int = 1) -> np.ndarray:
    """
    Find k-nearest neighbors of a query vector.

    Parameters
    ----------
    query : np.ndarray
        Query vector.
    vectors : np.ndarray
        Vectors to search.
    k : int, optional
        Number of nearest neighbors to return, by default 1.

    Returns
    -------
    np.ndarray
        The `k` nearest neighbors of `query` in `vectors`.
    """
    df = pd.DataFrame()
    distance = euclidean_distance(v1 = query, v2 = vectors)
    df['vectors'] = vectors
    df['distance'] = distance
    df_02 = df.sort_values(by='distance').loc[:k]
    return df_02['vectors']

## Other distance metrics

For this problem we'll write a new distance function and modify 
our nearest neighbors function to accept a distance metric.


Write a function that computes the [cosine distance](ttps://en.wikipedia.org/wiki/Cosine_similarity) between vectors.

In [9]:
from typing import Union

def cosine_distance(v1: np.ndarray, v2: np.ndarray) -> Union[float, np.ndarray]:
    """
    Compute the cosine distance between two vectors.

    Parameters
    ----------
    v1 : np.ndarray
        First vector.
    v2 : np.ndarray
        Second vector.

    Returns
    -------
    float
        Cosine distance between `v1` and `v2`.
    """
    cosine_similarity = (v1 * v2)/((np.sum(v1**2)**1/2)*(np.sum(v2**2)**1/2))
    cosine_distance = 1 - cosine_similarity
    return cosine_distance

**HINT** Please make sure you understand the difference between cosine similarity and cosine distance

Now, rewrite the `find_nearest_neighbors` function to accept a distance metric so you can use either Euclidean or Cosine distance

In [34]:
def find_nearest_neighbors(query: np.ndarray,
                           vectors: np.ndarray,
                           k: int = 1,
                           distance_metric="euclidean") -> np.ndarray:
    """
    Find k-nearest neighbors of a query vector with a configurable
    distance metric.

    Parameters
    ----------
    query : np.ndarray
        Query vector.
    vectors : np.ndarray
        Vectors to search.
    k : int, optional
        Number of nearest neighbors to return, by default 1.
    distance_metric : str, optional
        Distance metric to use, by default "euclidean".

    Returns
    -------
    np.ndarray
        The `k` nearest neighbors of `query` in `vectors`.
    """
    
    if distance_metric=='euclidean':
        df = pd.DataFrame()
        distance = euclidean_distance(v1 = query, v2 = vectors)
        df['vectors'] = vectors.tolist()
        df['distance'] = distance.tolist()
        print(df['distance'])
        df_02 = df.sort_values(by='distance').iloc[:k]
        return df_02['vectors']
    elif distance_metric=='cosine distance':
        df = pd.DataFrame()
        distance = euclidean_distance(v1 = query, v2 = vectors)
        df['vectors'] = vectors.tolist()
        df['distance'] = distance.tolist()
        print(df['distance'])
        df_02 = df.sort_values(by='distance').iloc[:k]
        return df_02['vectors']

## Exploration

Now that we have a nearest neighbors function that accepts a distance metric, <br/>
let's explore the differences between Euclidean distance and cosine distance.

Would you expect same or different answers?

In [39]:
# You might find this function useful

def generate_vectors(num_vectors: int, num_dim: int,
                     normalize: bool = True) -> np.ndarray:
    """
    Generate random embedding vectors.

    Parameters
    ----------
    num_vectors : int
        Number of vectors to generate.
    num_dim : int
        Dimensionality of the vectors.
    normalize : bool, optional
        Whether to normalize the vectors, by default True.

    Returns
    -------
    np.ndarray
        Randomly generated `num_vectors` vectors with `num_dim` dimensions.
    """
    vectors = np.random.rand(num_vectors, num_dim)
    if normalize:
        vectors /= np.linalg.norm(vectors, axis=1, keepdims=True)
    return vectors

In [41]:
query = np.array([0.2, 0.3, 0.4, 0.5, 0.6])
vectors = generate_vectors(num_vectors=10, num_dim=5, normalize=False)

find_vector = find_nearest_neighbors(query = query,
                           vectors = vectors,
                           k = 1,
                           distance_metric="euclidean")

print(f'query: {query}')
print(f'vectors: {vectors}')
print(f'find_vector: {find_vector}')

0    1.222576
1    1.222576
2    1.222576
3    1.222576
4    1.222576
5    1.222576
6    1.222576
7    1.222576
8    1.222576
9    1.222576
Name: distance, dtype: float64
query: [0.2 0.3 0.4 0.5 0.6]
vectors: [[0.1083521  0.55756687 0.43546841 0.62434578 0.31295147]
 [0.12722402 0.2319304  0.70496955 0.46455919 0.46607406]
 [0.19843375 0.3331213  0.61321528 0.62148295 0.29560145]
 [0.20150842 0.65882885 0.11463481 0.43348543 0.56946303]
 [0.03144048 0.71141262 0.09208703 0.11652098 0.6861825 ]
 [0.58525547 0.69007929 0.02864499 0.14725857 0.39844821]
 [0.26471119 0.32572368 0.32931878 0.62822332 0.56631853]
 [0.16015659 0.35922754 0.73018058 0.28634991 0.47973481]
 [0.50091289 0.54036726 0.59614597 0.15494261 0.27873332]
 [0.52181519 0.24576479 0.29457942 0.50333052 0.57200518]]
find_vector: 0    [0.10835209983575408, 0.5575668682903915, 0.43...
Name: vectors, dtype: object
